version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: volleynote-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
