version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: volleynote-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
